import * as THREE from 'three';
export const originalSand = [
    {
    name: 'barrier',
    dynamic: false,
    static: true,
    color: new THREE.Color(0xff0000),
},
{
    name: 'sand',
    dynamic: true,
    gravity: 1,
    sand: true,
    density: 1,
    color: new THREE.Color(0xffffaa),
},
{
    name: 'water',
    dynamic: true,
    gravity: 1,
    liquid: true,
    density: .5,
    color: new THREE.Color(0x0000ff),
    alpha: .5,
},
{
    name: 'copper',
    dynamic: true,
    static: true,
    falling: true,
    color: new THREE.Color(0xaa5511),
},
{
    name: 'wood',
    dynamic: true,
    static: true,
    falling: true,
    color: new THREE.Color(0x765432),
},
{
    name: 'iron',
    dynamic: true,
    static: true,
    falling: true,
    color: new THREE.Color(0xaaaaaa),
},
{
    name: 'gunpowder',
    dynamic: true,
    gravity: 1,
    sand: true,
    density: 2,
    color: new THREE.Color(0x444444),
},
{
    name: 'acid',
    dynamic: true,
    static: false,
    density: .5,
    liquid: true,
    gravity: 1,
    alpha: .5,
    color: new THREE.Color(0x009922),
},
{
    name: 'base',
    dynamic: true,
    gravity: 1,
    liquid: true,
    density: .5,
    alpha: .5,
    color: new THREE.Color(0x4444ff),
},
{
    name: 'fire',
    dynamic: true,
    gravity: 1,
    gas: true,
    density: .2,
    alpha: .9,
    emits: true,
    convert: [{
        prob: 0.02,
        value: 'smoke', //smoke
    }, {
        prob: 0.06,
        value: 'air',
    }],
    color: new THREE.Color(0xffff00),
},
{
    name: 'lava',
    dynamic: true,
    gravity: 1,
    liquid: true,
    density: 2,
    emits: true,
    alpha: .85,
    color: new THREE.Color(0xff8800),
},
{
    name: 'smoke',
    dynamic: true,
    gravity: 1,
    gas: true,
    density: .1,
    color: new THREE.Color(0xaaaaaa),
    convert: [{
        prob: 0.01,
        value: 'air',
    }],
},
{
    name: 'methane',
    dynamic: true,
    gravity: 1,
    gas: true,
    density: .15,
    color: new THREE.Color(0x221111),
    convert: [{
        prob: 0.0005,
        value: 'air',
    }],
},
{
    name: 'aciddepleated',
    dynamic: true,
    static: false,
    density: .8,
    liquid: true,
    gravity: 1,
    convert: [
        {
            prob: 0.999,
            value: 'acid',
        },
        {
            prob: 1,
            value: 'water',
        }
    ],
    color: new THREE.Color(0x009922),
},
{
    name: 'basedepleated',
    dynamic: true,
    gravity: 1,
    liquid: true,
    density: .4,
    color: new THREE.Color(0x4444ff),
    convert: [
        {
            prob: 0.999,
            value: 'base',
        },
        {
            prob: 1,
            value: 'water',
        }
    ],
},
{
    name: 'copper-charged',
    dynamic: true,
    static: true,
    falling: true,
    color: new THREE.Color(0xbb7733),
    charged: true,
},
{
    name: 'copper-rise',
    dynamic: true,
    static: true,
    falling: true,
    color: new THREE.Color(0x00ff00),
    charged: true,
},
{
    name: 'copper-fall',
    dynamic: true,
    static: true,
    falling: true,
    color: new THREE.Color(0xff0000),
    charged: true,
},
{
    name: 'burnedwood',
    dynamic: true,
    static: true,
    falling: true,
    color: new THREE.Color(0x432100),
},
{
    name: 'charredwood',
    dynamic: true,
    gravity: 1,
    sand: true,
    density: 1,
    color: new THREE.Color(0x333333),
},
{
    name: 'steam',
    dynamic: true,
    gravity: 1,
    gas: true,
    density: .1,
    color: new THREE.Color(0xaaaaff),
    alpha: .5,
    convert: [
    {
        prob: 0.0001,
        value: 'water',
    }
    ],
},
{
    name: 'coldrock',
    dynamic: true,
    sand: true,
    density: 1,
    gravity: 1,
    color: new THREE.Color(0x717171),
},
{
    name: 'warmrock',
    dynamic: true,
    sand: true,
    density: 1,
    gravity: 1,
    color: new THREE.Color(0x757575),
},
{
    name: 'rock',
    dynamic: true,
    sand: true,
    density: 1,
    gravity: 1,
    color: new THREE.Color(0x737373),
},
{
    name: 'hotrock',
    dynamic: true,
    sand: true,
    density: 1,
    gravity: 1,
    color: new THREE.Color(0x777777),
},
{
    name: 'stone',
    dynamic: false,
    static: true,
    color: new THREE.Color(0x707070),
},
{
    name: 'darkstone',
    dynamic: false,
    static: true,
    color: new THREE.Color(0x555555),
},
{
    name: 'grass',
    dynamic: true,
    static: true,
    falling: true,
    color: new THREE.Color(0x008822),
},
{
    name: 'dirt',
    dynamic: true,
    static: true,
    falling: true,
    color: new THREE.Color(0x654321),
},
{
    name: 'darkgrass',
    dynamic: true,
    static: true,
    falling: true,
    color: new THREE.Color(0x006611),
},
{
    name: 'darkdirt',
    dynamic: true,
    static: true,
    falling: true,
    color: new THREE.Color(0x432100),
},
{
    name: 'mud',
    dynamic: true,
    static: false,
    density: .8,
    sand: true,
    gravity: 1,
    color: new THREE.Color(0x321000),
},
{
    name: 'gold',
    dynamic: true,
    static: true,
    falling: true,
    charged: true,
    color: new THREE.Color(0xffff11),
},
{
    name: 'gold-charged',
    dynamic: true,
    static: true,
    falling: true,
    charged: true,
    color: new THREE.Color(0xffff11),
},
{
    name: 'gold-rise',
    dynamic: true,
    static: true,
    falling: true,
    color: new THREE.Color(0x00ff00),
},
{
    name: 'gold-fall',
    dynamic: true,
    static: true,
    falling: true,
    color: new THREE.Color(0xff0000),
},
{
    name: 'gold-powder',
    dynamic: true,
    static: true,
    falling: true,
    color: new THREE.Color(0xffff11),
},
{
    name: 'iron-charged',
    dynamic: true,
    static: true,
    falling: true,
    charged: true,
    color: new THREE.Color(0x888888),
},
{
    name: 'iron-rise',
    dynamic: true,
    static: true,
    falling: true,
    color: new THREE.Color(0x00ff00),
},
{
    name: 'iron-fall',
    dynamic: true,
    static: true,
    falling: true,
    color: new THREE.Color(0xff0000),
},
{
    name: 'iron-powder',
    dynamic: true,
    static: true,
    falling: true,
    color: new THREE.Color(0x888888),
},
{
    name: 'copper-powder',
    dynamic: true,
    static: true,
    falling: true,
    color: new THREE.Color(0xaa5511),
},
{
    name: 'quartz',
    dynamic: true,
    static: true,
    falling: true,
    color: new THREE.Color(0xffeeee),
},
{
    name: 'diamond',
    dynamic: true,
    static: true,
    falling: true,
    color: new THREE.Color(0xaaaaff),
},
{
    name: 'ruby',
    dynamic: true,
    static: true,
    falling: true,
    color: new THREE.Color(0xff0000),
},
{
    name: 'emerald',
    dynamic: true,
    static: true,
    falling: true,
    color: new THREE.Color(0x00ff00),
},
{
    name: 'quartz-rise',
    dynamic: true,
    static: true,
    falling: true,
    color: new THREE.Color(0xffeeee),
},
{
    name: 'diamond-rise',
    dynamic: true,
    static: true,
    falling: true,
    color: new THREE.Color(0xaaaaff),
},
{
    name: 'ruby-rise',
    dynamic: true,
    static: true,
    falling: true,
    color: new THREE.Color(0xff0000),
},
{
    name: 'emerald-rise',
    dynamic: true,
    static: true,
    falling: true,
    color: new THREE.Color(0x00ff00),
},
{
    name: 'quartz-fall',
    dynamic: true,
    static: true,
    falling: true,
    color: new THREE.Color(0xffeeee),
},
{
    name: 'diamond-fall',
    dynamic: true,
    static: true,
    falling: true,
    color: new THREE.Color(0xaaaaff),
},
{
    name: 'ruby-fall',
    dynamic: true,
    static: true,
    falling: true,
    color: new THREE.Color(0xff0000),
},
{
    name: 'emerald-fall',
    dynamic: true,
    static: true,
    falling: true,
    color: new THREE.Color(0x00ff00),
},
{
    name: 'quartz-charged',
    dynamic: true,
    static: true,
    falling: true,
    charged: true,
    color: new THREE.Color(0xffeeee),
},
{
    name: 'diamond-charged',
    dynamic: true,
    static: true,
    falling: true,
    charged: true,
    color: new THREE.Color(0xaaaaff),
},
{
    name: 'ruby-charged',
    dynamic: true,
    static: true,
    falling: true,
    charged: true,
    color: new THREE.Color(0xff0000),
},
{
    name: 'emerald-charged',
    dynamic: true,
    static: true,
    falling: true,
    charged: true,
    color: new THREE.Color(0x00ff00),
},
{
    name: 'quartz-powder',
    dynamic: true,
    gravity: 1,
    sand: true,
    density: 1,
    color: new THREE.Color(0xffeeee),
},
{
    name: 'diamond-powder',
    dynamic: true,
    gravity: 1,
    sand: true,
    density: 1,
    color: new THREE.Color(0xaaaaff),
},
{
    name: 'ruby-powder',
    dynamic: true,
    gravity: 1,
    sand: true,
    density: 1,
    color: new THREE.Color(0xff0000),
},
{
    name: 'emerald-powder',
    dynamic: true,
    gravity: 1,
    sand: true,
    density: 1,
    color: new THREE.Color(0x00ff00),
},
{
    name: 'oil',
    dynamic: true,
    static: false,
    density: .3,
    liquid: true,
    gravity: 1,
    color: new THREE.Color(0x332211),
},
{
    name: 'burningoil',
    dynamic: true,
    static: false,
    density: .2,
    liquid: true,
    gravity: 1,
    color: new THREE.Color(0x332211),
},
{
    name: 'limestone',
    dynamic: true,
    static: false,
    density: .5,
    sand: true,
    gravity: 1,
    color: new THREE.Color(0x88aa88),
},
{
    name: 'leaf',
    dynamic: true,
    static: true,
    falling: true,
    shadow: .5,
    color: new THREE.Color(0x007700),
},
{
    name: 'cactus',
    dynamic: true,
    static: true,
    falling: true,
    shadow: .5,
    color: new THREE.Color(0x005500),
},
{
    name: 'cactusspike',
    dynamic: true,
    static: true,
    falling: true,
    shadow: .5,
    color: new THREE.Color(0x000000),
},
{
    name: 'cactuswater',
    dynamic: true,
    static: true,
    falling: true,
    shadow: .5,
    color: new THREE.Color(0x005500),
},
{
    name: 'silicon',
    dynamic: true,
    gravity: 1,
    sand: true,
    density: 1,
    color: new THREE.Color(0xffffaa),
},
{
    name: 'silicon-charged',
    dynamic: true,
    gravity: 1,
    sand: true,
    density: 1,
    color: new THREE.Color(0xffffaa),
},
{
    name: 'silicon-rise',
    dynamic: true,
    gravity: 1,
    sand: true,
    density: 1,
    color: new THREE.Color(0x00ff00),
},
{
    name: 'silicon-fall',
    dynamic: true,
    gravity: 1,
    sand: true,
    density: 1,
    color: new THREE.Color(0xff0000),
},
{
    name: 'snow',
    dynamic: true,
    gravity: 1,
    sand: true,
    density: .1,
    color: new THREE.Color(0xffffff),
},
{
    name: 'ice',
    dynamic: true,
    static: true,
    falling: true,
    color: new THREE.Color(0xaaaaff),
},
{
    name: 'exhaust',
    dynamic: true,
    gravity: 1,
    sand: true,
    density: .1,
    color: new THREE.Color(0x888888),
    convert: [
        {
            prob: .1,
            value: 'air',
        },
    ],
},
{
    name: 'waterice',
    dynamic: true,
    static: true,
    falling: true,
    color: new THREE.Color(0x0000ff),
    alpha: .5,
    convert: [
        {
            prob: .1,
            value: 'water',
        },
        {
            prob: .1,
            value: 'ice',
        }
    ]
},
{
    name: 'unobtanium',
    dynamic: true,
    static: false,
    falling: true,
    emits: true,
    color: new THREE.Color(0xff00ff),
},
];

